apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/my-app/devfile-sample@sha256:06dacc9a45317d797da58d46fd463b280e1a357dda26c73f5877bc39c9c5a585
        name: my-nodejs
        resources: {}
status: {}
